name: Deploy to packagecloud
on:
  push:
    tags:
       - '*'

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: el
            dist: 7
          - name: fedora
            dist: 26
          - name: fedora
            dist: 27
          - name: fedora
            dist: 28
          - name: fedora
            dist: 29
        repository:
          - "1_10"
          - "2x"
          - "2_2"
          - "2_3"
          - "2_4"
    runs-on: ubuntu-latest
    env:
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      OS: ${{ matrix.os.name }}
      DIST: ${{ matrix.os.dist }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: deps
        run: gem install package_cloud

      - name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: packpack
        run: |
          git clone https://github.com/packpack/packpack.git packpack
          packpack/packpack
          ls -l build/

      - name: packagecloud
        run: package_cloud push tarantool/${{ matrix.repository }}/$OS/$DIST build/*.rpm

