name: Destroy-deployments

on:
  pull_request:
    paths:
      - 'doc/**/*'
    types:
      - closed
jobs:
  destroy-deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set branch name from source branch
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV

      - name: Remove dev server deployment at ${{env.DEPLOYMENT_NAME}}
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: "${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}"
          environment: "translation-${{env.BRANCH_NAME}}"
